### ISSUE TITLE
Dataset Query

### ISSUE THREAD

**Issue by ashinmarin** [Tathagatd96/CNN-keras-Cohn-kanade-dataset#2]
Is the dataset the CK+ one?
Also, how are you loading the data in the training file as the CK+ has directories in the format of cohn-kanade-images/S***/***?

**Comment by Tathagatd96** [comment]
@ashinmarin yes the dataset used is the CK+ dataset but it has been augmented as mentioned in the README. To get a better idea of the directory structure , kindly take a look at the fredtest_data.rar file. closing this issue.
